name: Greeting from Max

on: push

jobs:
  my-testing:
     runs-on: ubuntu-latest
       steps:
      - name: Print a greeting
         run: echo "Hello World Testing Job"


    my_deploy:
      runs-on: ubuntu-latest
        needs: [my-testing]
        steps:
       - name:  Print a greeting 
          run: echo "Hello World Deploy Job"  